###
POST http://localhost:8080/customers
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01
#Validation pass - Valid managers can add new customers

{
    "username": "good_user_1",
    "password": "01_user_01",
    "authorities": "ROLE_USER",
    "fullName": "User One",
    "nric": "S9942296C",
    "phone": "90123456",
    "address": "999 Tampines Road S999999",
    "active": true
}

###
PUT http://localhost:8080/customers/3
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01
#Validation pass - Valid managers can update customers 
#(phone, password, address, active)

{
    "username": "Cant Update",
    "password": "01_user_01",
    "authorities": "ROLE_USER",
    "fullName": "Cant Update",
    "nric": "S9111111B",
    "phone": "91111111",
    "address": "111 Tampines Road S111111",
    "active": false
}


###
PUT http://localhost:8080/customers/3
Content-Type: application/json
Authorization: Basic good_user_1 01_user_01
#Validation pass - Customer can update his OWN phone, address, password (other fields will get ignored)

{
    "username": "Cant Update",
    "password": "01_user_01",
    "authorities": "ROLE_USER",
    "fullName": "Cant Update",
    "nric": "S9999999Z",
    "phone": "91234246",
    "address": "1 Tampines Road S111001",
    "active": false
}


###
GET http://localhost:8080/customers
Accept: application/json
Authorization: Basic manager_1 01_manager_01
#Validation pass - Valid managers can view list of all customers

###
GET http://localhost:8080/customers
Accept: application/json
Authorization: Basic bad_manager 01_manager_01
#Validation fail - Invalid managers (wrong username) cannot view list of all customers

###
GET http://localhost:8080/customers
Accept: application/json
Authorization: Basic good_user_1 01_user_01
#Validation fail - Customers cannot view list of all customers


###
POST http://localhost:8080/customers
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01
#Validation pass - Valid managers can add new customers

{
    "username": "good_user_2",
    "password": "02_user_02",
    "authorities": "ROLE_USER",
    "fullName": "User Two",
    "nric": "T0046822Z",
    "phone": "92123262",
    "address": "222 Paya Lebar Road S222222",
    "active": true
}


###
POST http://localhost:8080/accounts
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01
# Validation pass - Valid managers can create new accounts

{
    "customer_id": 3,
    "balance": 100.0,
    "available_balance": 100.0
}

###
POST http://localhost:8080/accounts
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01
# Validation pass - Valid managers can create new accounts

{
    "customer_id": 4,
    "balance": 100000.0,
    "available_balance": 100000.0
}

###
GET http://localhost:8080/accounts
Accept: application/json
Authorization: Basic manager_1 01_manager_01
#Validation pass - Valid managers can view list of all accounts of customer

###
GET http://localhost:8080/accounts
Accept: application/json
Authorization: Basic good_user_1 01_user_01
#Validation pass - Customer can view all their OWN accounts

###
GET http://localhost:8080/accounts/1
Accept: application/json
Authorization: Basic good_user_1 01_user_01
#Validation pass - Customer can view their OWN specific account using accountId

###
POST http://localhost:8080/accounts/1/transactions
Content-Type: application/json
Authorization: Basic good_user_1 01_user_01
#Validation pass - Customers can create new transactions

{
    "sender": 1,
    "receiver": 2,
    "amount": 12345.0
}

###
GET http://localhost:8080/accounts/1/transactions
Accept: application/json
Authorization: Basic good_user_1 01_user_01
#Validation pass - Customers can view own account's transactions

###
GET http://localhost:8080/accounts/2/transactions
Accept: application/json
Authorization: Basic good_user_2 02_user_02
#Validation pass - Customers can view own account's transactions


###
POST http://localhost:8080/content
Content-Type: application/json
Authorization: Basic good_user_1 01_user_01
#Validation fail - Users cannot add new content

{
    "title":"The title of the advisory or news",
    "summary":"The short summary of the content item",
    "content": "The text of the content item",
    "link":"https://link.to.externalcontent"

}

###
POST http://localhost:8080/content
Content-Type: application/json
Authorization: Basic analyst_1 01_analyst_01
#Validation pass - Valid analysts can add new content

{
    "title":"The title of the advisory or news",
    "summary":"The short summary of the content item",
    "content": "The text of the content item",
    "link":"https://link.to.externalcontent"

}

###
POST http://localhost:8080/content
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01
#Validation pass - Valid managers can add new content

{
    "title":"The title of the advisory or news",
    "summary":"The short summary of the content item",
    "content": "The text of the content item",
    "link":"https://link.to.externalcontent"

}

###
GET http://localhost:8080/content
Accept: application/json
Authorization: Basic good_user_1 01_user_01
#Validation pass - Customers can view only approved content

###
GET http://localhost:8080/content
Accept: application/json
Authorization: Basic analyst_1 01_analyst_01
#Validation pass - Analysts can view all content

###
GET http://localhost:8080/content
Accept: application/json
Authorization: Basic manager_1 01_manager_01
#Validation pass - Managers can view all content

###
PUT http://localhost:8080/content/1
Content-Type: application/json
Authorization: Basic good_user_1 01_user_01
#Validation pass - Users cannot update content

{
    "title":"Title Not Updated",
    "summary":"Summary Not Updated",
    "content": "Goodbye",
    "link":"https://google.com",
    "approved": true
}

###
PUT http://localhost:8080/content/1
Content-Type: application/json
Authorization: Basic analyst_1 01_analyst_01
#Validation pass - Analysts can update everything but cannot approve content

{
    "title":"Title Changed",
    "summary":"Summary Changed",
    "content": "Hello",
    "link":"https://google.com",
    "approved": true
}

###
PUT http://localhost:8080/content/1
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01
#Validation pass - Managers can update everything and can approve content

{
    "title":"Title Changed Again",
    "summary":"Summary Changed Again",
    "content": "Hello Again",
    "link":"http://nooooooooooooooo.com",
    "approved": true
}

###
DELETE http://localhost:8080/content/1
Content-Type: application/json
Authorization: Basic good_user_1 01_user_01
#Validation pass - Users cannot delete content

###
DELETE http://localhost:8080/content/1
Content-Type: application/json
Authorization: Basic analyst_1 01_analyst_01
#Validation pass - Valid analysts can delete content

###
DELETE http://localhost:8080/content/1
Content-Type: application/json
Authorization: Basic manager_1 01_manager_01
#Validation pass - Valid managers can delete content
